package com.spring.kkaemiGG.domain.user;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import java.util.Optional;

public interface UserRepository extends JpaRepository<User, Long> {

    Optional<User> findByEmail(String email);

    @Query(value =
            "select concat('kkaemiGG', next value for nickname_number) " +
                    "as auto_generated_nickname " +
                    "from dual",
            nativeQuery = true)
    String getAutoGeneratedNickname();

}
